name: tobler
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - numpy
  - geopandas
  - pandas
  - numpy
  - rasterio
  - rasterstats
  - statsmodels
  - scikit-learn
  - scipy
  - libpysal
  - tqdm
  - pip
  - pygeos
  - mapclassify 
  - descartes
  - joblib
